### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Daniel15** [thibmaek/kid3-docker#1]
Discogs import broke recently, and the Kid3 developers only fixed it a few hours ago: https://github.com/KDE/kid3/commit/97464a9f8a042182b918dc436444eefc1ec5e5dc

Can you please push an update to this Docker container once that update is available in whichever repo you use for the app?

Thanks!

**Comment by thibmaek** [comment]
Aha! I thought Discogs being broken was on my end. I’ll keep an eye open for when this gets merged upstream and then update the container.

**Comment by thibmaek** [comment]
Then again, if @ufleisch updates this on their PPA, simple rebuilding the image should suffice since it will pull the latest version from the PPA

**Comment by thibmaek** [comment]
Keeping an eye open for this, seems like it hasn't been release upstream (ppa) yet so I can't fix this for now.

**Comment by thibmaek** [comment]
Hi @Daniel15 , I just pushed a new image to GHCR. Upstream Kid3 was pushed to their apt repo a few days ago so this new image should work for the Discogs fix.

Let me know if it does, will test it out myself later. Closing for now, assuming work is done here

**Comment by Daniel15** [comment]
Confirmed working once I got a Discogs personal access token from https://www.discogs.com/settings/developers and entered it into the "Token" field in the Discogs dialog in kid3. Thanks!
